Updated command prompt (PS1) and pwd alias to return exit status.

diff --git a/.bashrcd/bashrc_export b/.bashrcd/bashrc_export
--- a/.bashrcd/bashrc_export
+++ b/.bashrcd/bashrc_export
@@ -13,3 +13,22 @@ set -o vi
 stty -ixon
 # Pipe last command to less using shortcut Ctrl-L
 bind '"\C-l": "!! | less -X -F\r"'
+
+export PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs
+
+__prompt_command() {
+    local EXIT="$?"             # This needs to be first
+    PS1=""
+
+    local ColorOff="\[\033[0m\]" # Text Reset
+
+    local BRed="\[\033[1;31m\]"   # Red
+    local BGreen="\[\033[1;32m\]" # Green
+    local BBlue="\[\033[1;34m\]"  # Blue
+
+    if [ $EXIT != 0 ]; then
+        PS1+="${BRed}${EXIT}${ColorOff}|"      # Add red if exit code non 0
+    fi
+
+    PS1+="${BGreen}\u@\h:${ColorOff}${BBlue}\w${ColorOff}$ "
+}
